//
//  SearchInterfaces.swift
//  KTTC Lite
//
//  Created by Ярослав Стрельников on 26.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol SearchWireframeInterface: WireframeInterface {
}

protocol SearchViewInterface: ViewInterface {
    func reloadData()
}

protocol SearchPresenterInterface: PresenterInterface {
    var formatter: SearchFormatterInterface { get }
    func didSearchUsers(by keyword: String, with gameType: KTTCApi.GameType, completed: @escaping (() -> Void))
    func didFinish()
}

protocol SearchFormatterInterface: FormatterInterface {
    var users: [User] { get set }
}

protocol SearchInteractorInterface: InteractorInterface {
    func searchUser(bySearchKeyword keyword: String, withGameType gameType: KTTCApi.GameType, completed: @escaping (() -> Void))
}
