//
//  SearchFormatter.swift
//  KTTC Lite
//
//  Created by Ярослав Стрельников on 26.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SearchFormatter {
    var users: [User] = []
}

// MARK: - Extensions -

extension SearchFormatter: SearchFormatterInterface {
}
