//
//  SearchInteractor.swift
//  KTTC Lite
//
//  Created by Ярослав Стрельников on 26.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class SearchInteractor {
    weak var presenter: SearchPresenterInterface?
    let api: KTTCApi = KTTCApi()
}

// MARK: - Extensions -

extension SearchInteractor: SearchInteractorInterface {
    func searchUser(bySearchKeyword keyword: String, withGameType gameType: KTTCApi.GameType, completed: @escaping (() -> Void)) {
        api.request(with: UserInfoWithArray<User>.self, gameType: gameType, .account, .list, [.search: keyword.trimmingCharacters(in: .whitespacesAndNewlines)]).start { [weak self] users in
            self?.presenter?.formatter.users = users.data ?? []
        } error: { error in
            print(error)
        } completed: { [weak self] in
            guard let self = self else { return }
            self.presenter?.didFinish()
            completed()
        }
    }
}
