//
//  StatisticsInterfaces.swift
//  KTTC Lite
//
//  Created by Ярослав Стрельников on 26.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import ObjectMapper

protocol StatisticsWireframeInterface: WireframeInterface {
}

protocol StatisticsViewInterface: ViewInterface {
    var dataSource: DataSource { get set }
    var snapshot: Snapshot { get set }
    var isBlitz: Bool { get }
    func error(withMessage message: String)
    func stopLoading()
    func setXVMTitle(withColor color: UIColor)
}

protocol StatisticsPresenterInterface: PresenterInterface {
    var formatter: StatisticsFormatterInterface { get }
    var view: StatisticsViewInterface { get }
    func didRunProcess<T: Mappable>(with model: T.Type, accountId: Int, gameType: KTTCApi.GameType, nickName: String?)
}

protocol StatisticsFormatterInterface: FormatterInterface {
    var needCalculateData: NeedCalculateData { get set }
    func makeDataSource(collectionView: UICollectionView) -> DataSource
    func makeSnapshot() -> Snapshot
    func finish()
}

protocol StatisticsInteractorInterface: InteractorInterface {
    func getStatistics<T: Mappable>(with model: T.Type, with accountId: Int, from gameType: KTTCApi.GameType)
}
